# Generated by Django 6.0.6 on 2026-06-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el producto está activo para los clientes'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Subcategorías a las que pertenece el producto', related_name='multi_products', to='catalog.category'),
        ),
    ]
