# Generated by Django 6.0.6 on 2026-06-12 00:43

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_active_product_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
